workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.19.0
      xcode: latest
    triggering:   # trigger a build on GitHub push
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          flutter --version
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS app
        script: |
          flutter build ios --no-codesign
